### ISSUE TITLE
build warnings for igraph_i_set_attribute_table and g_memmove

### ISSUE THREAD

**Issue by beenhuang** [shadow/tgen#26]
When I installed tgen on Fedora34, I encountered the following warnings in the pictures. How should I fix the bugs?
<img width="1024" alt="截屏2021-12-13 下午8 30 49" src="https://user-images.githubusercontent.com/30388171/145824779-0c02a322-9456-4d68-9ca0-45de5d7d83a3.png">
<img width="997" alt="截屏2021-12-13 下午8 31 18" src="https://user-images.githubusercontent.com/30388171/145824786-075dbf17-dba2-456f-b59e-2e0f123e259b.png">

**Comment by sporksmith** [comment]
I don't think these will cause any issues at runtime. The warnings are because the symbols are deprecated and so will likely go away in the future, which will break the build if we haven't replaced their usage by then.

From a quick look, it seems `g_memmove` should be replaced by `memmove`, and `igraph_i_set_attribute_table` with [`igraph_set_attribute_table`](https://igraph.org/c/doc/igraph-Attributes.html#igraph_set_attribute_table)
